# Generated by Django 3.0.6 on 2020-05-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200524_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
